### ISSUE TITLE
The `org-bibtex' library was removed in Emacs version 27.1.

### ISSUE THREAD

**Issue by iT-Boyer** [emacsattic/org-mac-protocol#1]
The `org-bibtex` library was removed in Emacs version 27.1.
(require 'oX You should depend on (emacs "24.1") if you need `org-bibtex`.

**Comment by tarsius** [comment]
The error message you posted seems mangled, in particular this part `(require 'oX You`. Maybe the mangled part contains more useful information?

> The org-bibtex library was removed in Emacs version 27.1.

Was that part of the error message, or is it your interpretation?

Also, what generated that error message? The byte-compiler?

I would assume the fix is to replace `(require 'org-bibtex)` with `(require 'new-name-of-that-library)`. You could help me fix this by finding out what the new name. Ideally you would determine the commit in which the library was renamed and provided the commit hash so that I can confirm that.

Better yet, you could open a pull-request, which makes the required change. The commit message should mention the Org commit that makes it necessary.

**Comment by tarsius** [comment]
Oh. I thought this was a repository in the Emacs Orphanage, not the Emacs**attic**. I don't maintain packages in the attic. But if you open a pull-request that looks sound and clearly describes what it does and why, then I would be willing to merge it.
